### ISSUE TITLE
Shadowrocket 设置无效

### ISSUE THREAD

**Issue by zhaoyou** [Semporia/TikTok-Unlock#13]
- TikTok version v18.5.0 (1850160)
- Shadowrocket  2.1.77 (1245)
- iOS 14.4 

根据步骤设置了，同时安装了证书，并且信任了。Tiktok首页还是无法刷出来

**Comment by 0906570770** [comment]
Tiktok 20.3

**Comment by Semporia** [comment]
TikTok走的哪里节点？

**Comment by zhaoyou** [comment]
卸载TikTok，重新安装已解决。（再也不敢手贱升级了）
