### ISSUE TITLE
关闭应用，重新启动Tik Tok，MitM解密失败

### ISSUE THREAD

**Issue by lampb0y** [Semporia/TikTok-Unlock#130]
操作步骤：

1. 梯子应用：Quanmult X（MitM证书已配置并信任）(重写已开启）
2. 下载21.1.0版本并安装
3. 打开21.1.0版本正常打开提示需要AppStore更新
4. 更新至23.3.0
5. 启动成功，注册/直播/点赞功能正常
6. 退出Tik Tok重新打开
7. 提示“无网络连接”，日志显示 api*tiktokv.com MitM解析红色

**Comment by lampb0y** [comment]
device: iPad mini 5
os version: 15.1

**Comment by hzhr** [comment]
你在 21.1.0 版本登陆账号没有？

**Comment by AisukaYuki** [comment]
我之前也是这样，更新之后再启动就mitm失败。试试不要用手机的appstore更新,用抓包软件跨版本多更新几个版本21到22到23最新。

**Comment by lampb0y** [comment]
> 你在 21.1.0 版本登陆账号没有？

登录不了，一上21.1.0就告诉我要升级了

**Comment by lampb0y** [comment]
> 我之前也是这样，更新之后再启动就mitm失败。试试不要用手机的appstore更新,用抓包软件跨版本多更新几个版本21到22到23最新。

那大佬现在你这边Okay能正常解析吗？

**Comment by hzhr** [comment]
> > 你在 21.1.0 版本登陆账号没有？
> 
> 
> 
> 登录不了，一上21.1.0就告诉我要升级了

21.1.0打开后，别停留在首页，马上切换为个人资料页，再登陆账号，看是否稳定使用了？再考虑是否要升级。

**Comment by jianhuihi** [comment]
> > > 你在 21.1.0 版本登陆账号没有？
> > 
> > 
> > 登录不了，一上21.1.0就告诉我要升级了
> 
> 21.1.0打开后，别停留在首页，马上切换为个人资料页，再登陆账号，看是否稳定使用了？再考虑是否要升级。

不停留首页的目的是啥？ 我是测试21.1.0版本各个功能都正常了才开始升级 结果升级完就废了！

**Comment by jianhuihi** [comment]
![image](https://user-images.githubusercontent.com/4176545/155912431-0eceeb05-8b59-4b5d-b8fa-89ca0286a046.jpeg)

21.1.0 升级 22.8 再升级23.3 依旧跪

**Comment by hzhr** [comment]
> > > > 你在 21.1.0 版本登陆账号没有？
> 
> > > 
> 
> > > 
> 
> > > 登录不了，一上21.1.0就告诉我要升级了
> 
> > 
> 
> > 21.1.0打开后，别停留在首页，马上切换为个人资料页，再登陆账号，看是否稳定使用了？再考虑是否要升级。
> 
> 
> 
> 不停留首页的目的是啥？ 我是测试21.1.0版本各个功能都正常了才开始升级 结果升级完就废了！
> 
> 
> 
> 另外：你有没有关定位 改时区等操作呢？

现在打开 21.1.0 首页，如果没有登陆账号，会强制你升级；赶紧切走是为了能及时登陆账号，登陆账号后，回到首页就不会再提示升级，其他功能也正常。
如果再升级不行，那可能是方法不行了。
没有改过定位、时区，可以看看是否这的影响。

**Comment by lampb0y** [comment]
@jianhuihi 看起来自己抓包的21.1.0才能用，别人的ID下下来的不能用，你是自己抓的包吗

**Comment by lampb0y** [comment]
3.2 22:37更新 自己的Apple ID也没用
是否问题在于我的iCloud帐号是国区而Apple Store是美区

**Comment by lampb0y** [comment]
3.2 22:37更新 自己的Apple ID也没用
是否问题在于我的iCloud帐号是国区而Apple Store是美区

**Comment by lampb0y** [comment]
iCloud/App Store均使用美区ID，抓了21.1.0安装在iPad上，可以体验一个小时以上了，mitm解析也正常，我想可能明天再看一下，如果可以的话就升级23.3.0

**Comment by lampb0y** [comment]
把mitm关了就能用了……
