### ISSUE TITLE
TikTok直播打不开

### ISSUE THREAD

**Issue by caiciyu** [Semporia/TikTok-Unlock#150]
不知道大家的直播是否能打开，我这是21.0版本的，全程都挂的代理

**Comment by seoho8908** [comment]
我一切正常。可以打开。
Live直播，关注，推荐都可以看。点赞，评论，发视频也都OK。
TikTok 版本：23.7

**Comment by caiciyu** [comment]
> 我一切正常。可以打开。 Live直播，关注，推荐都可以看。点赞，评论，发视频也都OK。 TikTok 版本：23.7

我这抓包安装21.0然后升级成23.7就不能用了，用的圈X，能分享一下你的升级方案吗？

**Comment by caiciyu** [comment]
我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样

**Comment by fhqievg** [comment]
> 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
正常商店升级？

**Comment by fhqievg** [comment]
> 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样

正常商店升级？

**Comment by caiciyu** [comment]
> > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> 
> 正常商店升级？

是的，就是在app store上升级的

**Comment by fhqievg** [comment]
> > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> 
> > 
> 
> > 正常商店升级？
> 
> 
> 
> 是的，就是在app store上升级的

我刚试着去升级了不行，刷着刷着就显示无网络连接

**Comment by caiciyu** [comment]
> > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> > 
> > 
> > > 
> > 
> > 
> > > 正常商店升级？
> > 
> > 
> > 是的，就是在app store上升级的
> 
> 我刚试着去升级了不行，刷着刷着就显示无网络连接

我这边确实是可以一直看的，这我就不知道为啥了

**Comment by fhqievg** [comment]
> 我一切正常。可以打开。
> 
> Live直播，关注，推荐都可以看。点赞，评论，发视频也都OK。
> 
> TikTok 版本：23.7
> 
> 

你好，我现在是21.1，一去商店升级23.7就用不了，能赐教下你怎么操作的吗？

**Comment by fhqievg** [comment]
> > > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 正常商店升级？
> 
> > > 
> 
> > > 
> 
> > > 是的，就是在app store上升级的
> 
> > 
> 
> > 我刚试着去升级了不行，刷着刷着就显示无网络连接
> 
> 
> 
> 我这边确实是可以一直看的，这我就不知道为啥了

哥们，你配置文件是选用的哪个国家的？

**Comment by fhqievg** [comment]
> > > > > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 正常商店升级？
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 是的，就是在app store上升级的
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我刚试着去升级了不行，刷着刷着就显示无网络连接
> 
> > > 
> 
> > > 
> 
> > > 我这边确实是可以一直看的，这我就不知道为啥了
> 
> > 
> 
> > 哥们，你配置文件是选用的哪个国家的？
> 
> 
> 
> 我用的是日本的配置文件，我现在清后台也可以用，算是完美升级了

好的，谢谢

**Comment by WenchenWang** [comment]
> > > > > > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > > 正常商店升级？
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 是的，就是在app store上升级的
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 我刚试着去升级了不行，刷着刷着就显示无网络连接
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 我这边确实是可以一直看的，这我就不知道为啥了
> > 
> > > 
> > 
> > > 哥们，你配置文件是选用的哪个国家的？
> > 
> > 
> > 
> > 我用的是日本的配置文件，我现在清后台也可以用，算是完美升级了
> 
> 好的，谢谢

**Comment by WenchenWang** [comment]
> > > > > > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > > 正常商店升级？
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 是的，就是在app store上升级的
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 我刚试着去升级了不行，刷着刷着就显示无网络连接
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 我这边确实是可以一直看的，这我就不知道为啥了
> > 
> > > 
> > 
> > > 哥们，你配置文件是选用的哪个国家的？
> > 
> > 
> > 
> > 我用的是日本的配置文件，我现在清后台也可以用，算是完美升级了
> 
> 好的，谢谢
请问你解决了吗？我也是无网络连接，本来好好的，升级后也能看，到晚上就直接无网络连接了

**Comment by fhqievg** [comment]
> > > > > > > > > 我升级到23.7版本之后，发现直播可以看了，目前没有清后台，一直可以用，不知道清理后台之后会怎么样
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > > > 正常商店升级？
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > >
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > > 是的，就是在app store上升级的
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > 
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > > 我刚试着去升级了不行，刷着刷着就显示无网络连接
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > 我这边确实是可以一直看的，这我就不知道为啥了
> > > 
> > > > 
> > > 
> > > > 哥们，你配置文件是选用的哪个国家的？
> > > 
> > > 
> > > 
> > > 我用的是日本的配置文件，我现在清后台也可以用，算是完美升级了
> > 
> > 好的，谢谢
> 请问你解决了吗？我也是无网络连接，本来好好的，升级后也能看，到晚上就直接无网络连接了
> 

不能关闭代理，一关闭代理tiktok连接过国内网络后就会无网络连接，一直开着代理就不会出现这种情况

**Comment by gitcook** [comment]
IOS 15.4 21.1 有些直播秒刷出来，有些怎么也刷不出来  ，圈X 网络日志里面 显示有一个UDP的链接被reject  ，不晓得是不是 节点未开启UDP的原因

**Comment by WenchenWang** [comment]
> IOS 15.4 21.1 有些直播秒刷出来，有些怎么也刷不出来 ，圈X 网络日志里面 显示有一个UDP的链接被reject ，不晓得是不是 节点未开启UDP的原因

我也是reject 这种情况如何处理？

**Comment by zzhx2998** [comment]
怎么退订这个，邮件一直来
