### ISSUE TITLE
升级最新版显示无网络连接

### ISSUE THREAD

**Issue by WenchenWang** [Semporia/TikTok-Unlock#156]
抓包以前版本可以看，然后升级最新版本也可以看，但是到了晚上就在刚才，重新打开就提示无网络连接，啥情况？

**Comment by fhqievg** [comment]
> 抓包以前版本可以看，然后升级最新版本也可以看，但是到了晚上就在刚才，重新打开就提示无网络连接，啥情况？

不能关闭代理，一关闭代理tiktok连接过国内网络后就会无网络连接，一直开着代理就不会出现这种情况

**Comment by WenchenWang** [comment]
就是关代理的时候不能不小心打开tiktok 吗？

**Comment by fhqievg** [comment]
> 就是关代理的时候不能不小心打开tiktok 吗？

最好还是别关，如果习惯用的时候打开代理，不用就关代理，建议用21.1，我现在就是用的21.1，比较稳

**Comment by WenchenWang** [comment]
嗯 目前我就用21.0了 真烦。。
