### ISSUE TITLE
iOS15.4.1已经不支持 itunes12.6.5.3

### ISSUE THREAD

**Issue by nekore** [Semporia/TikTok-Unlock#165]
看到介绍里面说支持到iOS15.5，实测15.4.1已经不能用这个itunes版本连接了

**Comment by liruishan1995** [comment]
用这个版本主要是抓包旧版程序，不用连接手机，能正常登录账号进商店就行

**Comment by nekore** [comment]
> 用这个版本主要是抓包旧版程序，不用连接手机，能正常登录账号进商店就行。抓包后用爱思助手安装应用到手机

已经在用爱思助手安装了，就是速度慢一些。
