### ISSUE TITLE
TikTok v18.7.5 shadowroeket 最新规则 无效

### ISSUE THREAD

**Issue by JzwOnly** [Semporia/TikTok-Unlock#17]
TikTok v18.7.5最新版本，shadowroeket添加规则，证书信任，使用配置模式开启，打开TikTok 无法刷出视频

**Comment by CurtisWong458** [comment]
> TikTok v18.7.5最新版本，shadowroeket添加规则，证书信任，使用配置模式开启，打开TikTok 无法刷出视频

14.4.1系统，小火箭最新版，TT最新美版 没问题

**Comment by Semporia** [comment]
> TikTok v18.7.5最新版本，shadowroeket添加规则，证书信任，使用配置模式开启，打开TikTok 无法刷出视频

请复查节点走向，最好提供日志，才好分析原因！

**Comment by JzwOnly** [comment]
@Semporia 我的问题，小火箭好久没更新了，今天早上更新完可以了 谢谢
