### ISSUE TITLE
24.4.3可用

### ISSUE THREAD

**Issue by jupiter219** [Semporia/TikTok-Unlock#179]
从21升上来的，参考前面兄弟的方法。升级后第一次可以正常打开浏览，而后就失效了。此时不要卸载，使用apple configurator强制重新安装21版本，此时打开21依然无法加载，而后再次从app store升级至最新版，此时再次打开即可正常使用。

**Comment by nuaalm** [comment]
你运气好，不可能的事，我试了n次，已经放弃了

**Comment by Dashan-IZ** [comment]
都配置好了，但是用一段时间就会显示，请连接到互联网重试

**Comment by seoho8908** [comment]
> 你运气好，不可能的事，我试了n次，已经放弃了

Surge下 24.4.3，一切正常。

**Comment by nuaalm** [comment]
所以别折腾了> 都配置好了，但是用一段时间就会显示，请连接到互联网重试
