### ISSUE TITLE
quanulmult x换区

### ISSUE THREAD

**Issue by maple-spirit** [Semporia/TikTok-Unlock#200]
Quantumult X换区有点看不明白，是[rewrite_remote]链接中的地区代码不用改，直接在[rewrite_local]中加要要换其它区的代码，还是这两个地方的代码都要改？

**Comment by seoho8908** [comment]
> Quantumult X换区有点看不明白，是[rewrite_remote]链接中的地区代码不用改，直接在[rewrite_local]中加要要换其它区的代码，还是这两个地方的代码都要改？

圈X用不来。我用圈X设置没一次成功的。😭

目前我用surge，一切OK

**Comment by maple-spirit** [comment]
> 

可以用啊，我就是看不太明白它里面最后说那个换区

**Comment by Chen529b** [comment]
我也是有同样的疑惑，我直接改了但是并没有换区 而且还看不到左上角那个直播界面了

**Comment by maple-spirit** [comment]
>
