### ISSUE TITLE
ipadpro2021wifi版无法解锁tiktok，已抓包旧版

### ISSUE THREAD

**Issue by HJS168** [Semporia/TikTok-Unlock#235]
ipadpro2021 WiFi版，版本是ipados15.6，用的跟手机一样的圈x配置文件，tiktok也抓的21.1.0，手机可以正常观看，升级到最新版都没问题，ipad就不行，一进去就黑屏，有兄弟ipadpro能成功解锁tiktok吗，实在找不到是啥原因

**Comment by HJS168** [comment]
有大佬能帮我解答一下吗，是不是wifi版的无法解锁？

**Comment by HJS168** [comment]
![image](https://user-images.githubusercontent.com/87559217/180644218-34730be1-da1d-4663-8c99-721e460fc936.png)![image](https://user-images.githubusercontent.com/87559217/180644221-07a53767-354f-42b9-b0a4-234ed8c62dd6.png)![image](https://user-images.githubusercontent.com/87559217/180644226-f117220a-e165-44cc-b5b4-aaa0b5524392.png)

**Comment by seoho8908** [comment]
> ipadpro2021 WiFi版，版本是ipados15.6，用的跟手机一样的圈x配置文件，tiktok也抓的21.1.0，手机可以正常观看，升级到最新版都没问题，ipad就不行，一进去就黑屏，有兄弟ipadpro能成功解锁tiktok吗，实在找不到是啥原因

建议用Surge。我之前也尝试用过圈X，一直无法解锁成功。用Surge解锁就一切OK。

**Comment by lingfengsanhao** [comment]
> ipadpro2021 WiFi版，版本是ipados15.6，用的跟手机一样的圈x配置文件，tiktok也抓的21.1.0，手机可以正常观看，升级到最新版都没问题，ipad就不行，一进去就黑屏，有兄弟ipadpro能成功解锁tiktok吗，实在找不到是啥原因

这个项目叫拔卡看tiktok，ipadpro都没有卡，为什么要mitm？直接下载最新的用的，看你描述，就是没有改通用-语言与地区里面的地区，把这个地区改成你想观看的地区，分流节点同理，这样就可以直接看了，记得把字节所有app卸载干净了再试

**Comment by HJS168** [comment]
好的，谢谢兄弟，我去试一下

**Comment by HJS168** [comment]
![image](https://user-images.githubusercontent.com/87559217/180754178-1d8b5489-7faa-49a1-aaa6-9e11b27cc6d4.png)
改了地区跟分流，还是不行😭

**Comment by lingfengsanhao** [comment]
是可以刷视频不能登录？

**Comment by HJS168** [comment]
都不行

**Comment by HJS168** [comment]
还是一样的黑屏

**Comment by HJS168** [comment]
怪得要死

**Comment by lingfengsanhao** [comment]
你抓包21.1.0看下会不会黑屏

**Comment by lingfengsanhao** [comment]
字节的app都卸载干净（ipad存储空间-删除app）重装了（特别抖音），重装后改地区再代理打开，不可能不可以的，我iPad也在用，app重装，地区修改，开启分流，不开启重写你自己检查一下哪步没做

**Comment by Semporia** [comment]
iPad Wi-Fi版本请直接下载AppStore版本，添加分流即可！
