### ISSUE TITLE
小火箭2.1.75 & TikTok 21.1.0 黑屏，配置文件导出如下

### ISSUE THREAD

**Issue by RichieMay** [Semporia/TikTok-Unlock#249]
# Shadowrocket: 2022-08-22 14:45:00
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, e.crashlytics.com, captive.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = 

[Rule]
DOMAIN-KEYWORD,google,PROXY,force-remote-dns
DOMAIN,p16-tiktokcdn-com.akamaized.net,PROXY
DOMAIN-SUFFIX,byteoversea.com,PROXY
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,ibyteimg.com,PROXY
DOMAIN-SUFFIX,ipstatp.com,PROXY
DOMAIN-SUFFIX,muscdn.com,PROXY
DOMAIN-SUFFIX,musical.ly,PROXY
DOMAIN-SUFFIX,sgpstatp.com,PROXY
DOMAIN-SUFFIX,snssdk.com,PROXY
DOMAIN-SUFFIX,tik-tokapi.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY
DOMAIN-SUFFIX,tiktokv.com,PROXY
DOMAIN-KEYWORD,-tiktokcdn-com,PROXY
USER-AGENT,TikTok*,PROXY
FINAL,PROXY

[Host]
ads.google.com = 127.0.0.1
localhost = 127.0.0.1

[URL Rewrite]
^http://(www.)?g.cn https://www.google.com 302
^http://(www.)?google.cn https://www.google.com 302
^http://reject.example.com reject 
(?<=_region=)CN(?=&) TW 307
(?<=&mcc_mnc=)4 2 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[MITM]
ca-passphrase = Shadowrocket
ca-p12 = 证书内容
hostname = *.tiktokv.com,*.musical.ly,*.byteoversea.com,*.tik-tokapi.com,-*snssdk.com,-*amemv.com

**Comment by RichieMay** [comment]
小火箭记得打开HTTPS解密、安装证书以及去关于本机中信任根证书！

**Comment by Noe1Yoo** [comment]
小火箭哪里添加或修改hostname ？
