### ISSUE TITLE
求版本号

### ISSUE THREAD

**Issue by happinesslijian** [Semporia/TikTok-Unlock#254]
请问谁知道V25.7.1版本号是多少？麻烦回复一下。
问题描述：
之前的手机使用V25.7.1版本，可以登录，可以评论，可以点赞，可以发视频。
现在的手机无法使用V25.7.1版本(因为我不知道V25.7.1版本号，所以抓不到包)，从App Store更新直接就是最新版V25.8.0
而V25.8.0目前无法使用
另外 @Semporia 群主创建一个TG群吧 可供大家交流心得 Thanks♪(･ω･)ﾉ

**Comment by Semporia** [comment]
25.8正常使用没问题，历史版本下载看REDME的教程。

**Comment by happinesslijian** [comment]
问题1：
再次确认一下25.8正常使用没问题吗？可以正常评论、点赞、发视频吗？可以正常登录吗?(如果可以登录，请透露一下您是用什么方式登录的？邮箱还是第三方 比如推特，还是其他什么方式?)
问题2:：
历史版本我会操作，在抓出来的列表当中，最新的是V24.X.X(因为电脑没在身边，因此不能截图)拿不到V25.X.X
因此才询问V25.7.1版本号是多少

**Comment by happinesslijian** [comment]
> 



> 25.8正常使用没问题，历史版本下载看REDME的教程。

问题1：
再次确认一下25.8正常使用没问题吗？可以正常评论、点赞、发视频吗？可以正常登录吗?(如果可以登录，请透露一下您是用什么方式登录的？邮箱还是第三方 比如推特，还是其他什么方式?)
问题2:：
历史版本我会操作，在抓出来的列表当中，最新的是V24.X.X(因为电脑没在身边，因此不能截图)拿不到V25.X.X
因此才询问V25.7.1版本号是多少

**Comment by Semporia** [comment]
当然都没有问题，登录方式用电话号码登陆。

**Comment by happinesslijian** [comment]
> 当然都没有问题，登录方式用电话号码登陆。

我整理一下思路：
1 所有的升级都是基于版本21.1.0进行升级
2 升级是在App Store里升级
这么理解对不？ @Semporia 
另外，有意向创建一个TG群吗？

**Comment by Semporia** [comment]
21.1.0正常可用后在AppStore升级至新版。
