### ISSUE TITLE
新版本一切正常

### ISSUE THREAD

**Issue by ClydeTime** [Semporia/TikTok-Unlock#289]
欢迎讨论，也会尽可能帮忙协助解决问题

**Comment by thinktip** [comment]
前几天发了一个视频后直接被封号。然后从头安装，twitter登录，可以刷视频，但不能点赞，不能关注。

**Comment by ClydeTime** [comment]
> 前几天发了一个视频后直接被封号。然后从头安装，twitter登录，可以刷视频，但不能点赞，不能关注。

目前只有观看视频习惯，并无上传需求，可以关注点赞，请尝试以下规则(圈X/联通 only)，不保证绝对解决问题
奉上 https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/TikTok/TikTok-JP.conf

**Comment by CurtisWong458** [comment]
最新版26.6.1完全没问题，之前下载安装21.1.0旧版本点赞评论关注还有发视频都可以。然后再升级安装26.6.1依然没问题
