### ISSUE TITLE
是不支持iPad吗？同样的操作，iPhone可以，iPad不可以，看日志，两者是相同的。

### ISSUE THREAD

**Issue by zhangwengsheng** [Semporia/TikTok-Unlock#293]
型号：iPad Pro11寸 2020 ；
系统版本：iOS16

**Comment by CHENYY0214** [comment]
ipad本来就没卡，直接代理就能看

**Comment by seoho8908** [comment]
> 型号：iPad Pro11寸 2020 ；
> 
> 系统版本：iOS16

iPad啥版本？Wi-Fi版？蜂窝数据版？
Wi-Fi版本的不需要解锁，开了VPN就可以看。

**Comment by zhangwengsheng** [comment]
> 

我回退了在iPad上的操作，可惜还是不行，可能我搞坏了什么东西吧。

**Comment by zhangwengsheng** [comment]
> > 型号：iPad Pro11寸 2020 ；
> > 
> > 系统版本：iOS16
> 
> iPad啥版本？Wi-Fi版？蜂窝数据版？
> Wi-Fi版本的不需要解锁，开了VPN就可以看。

Wi-Fi 版本，我的还是不行。

**Comment by q123336196** [comment]
> > ipad本来就没有卡，直接代理就可以看
> 
> 我回去了在iPad上的操作，可惜还是不行，可能我搞坏了什么东西吧。

很简单  ipad 地区改为美国，小火煎配置文件还原，小伙剑描述文件删除，美区id直接下载tiktok  就可以了

**Comment by Semporia** [comment]
仅需添加分流，然后直接在AppStore中下载TikTok最新版本既可以正常使用！
