### ISSUE TITLE
小火箭第三步添加分流怎么搞

### ISSUE THREAD

**Issue by liugangya** [Semporia/TikTok-Unlock#31]
或者怎么添加规则，作者能说清楚吗？

**Comment by liugangya** [comment]
问题解决方法详见https://github.com/Pinanchen/TikTok-Free

**Comment by Semporia** [comment]
https://merlinblog.xyz/wiki/shadowrocket.html

教程看一下呢！

**Comment by Pankaipeng** [comment]
最后一步，編輯後點擊返回 – 點擊編輯配置 – HTTPS解密 — 生成證書 – 安裝證書。

**Comment by saibanCFY** [comment]
> https://merlinblog.xyz/wiki/shadowrocket.html

打不开啊

**Comment by Semporia** [comment]
不出去怎么看得到呢？

<img width="1531" alt="圖片" src="https://user-images.githubusercontent.com/29939899/121116110-9e104900-c848-11eb-97da-690f761a8ca3.png">

**Comment by JVAVEngineer** [comment]
关键是在哪里填.list地址？

**Comment by myluke** [comment]
> 关键是在哪里填.list地址？

这list 要手填，我研究了半天，就是添加规则

**Comment by qwetrz007sh** [comment]
解锁失败

**Comment by 12VD2** [comment]
> > 关键是在哪里填.list地址？
> 
> 这list 要手填，我研究了半天，就是添加规则

是在配置模块后，编辑配置文件添加规则么

**Comment by hdc8899** [comment]
> > > 关键是在哪里填.list地址？
> > 
> > 
> > 这list 要手填，我研究了半天，就是添加规则
> 
> 是在配置模块后，编辑配置文件添加规则么

请问你解决了吗？怎么操作呀

**Comment by Semporia** [comment]
配置 → 编辑配置（ ℹ️ ） → 规则 → 添加规则 → 类型选 【 rule-set 】

**Comment by akudamatata** [comment]
> 配置 → 编辑配置（ ℹ️ ） → 规则 → 添加规则 → 类型选 【 rule-set 】

奶奶的 看了一圈issues  终于找到第三部在哪里弄了

**Comment by happyaguang** [comment]
> 配置 → 编辑配置（ ℹ️ ） → 规则 → 添加规则 → 类型选 【 rule-set 】

哈哈，长篇大论，就最后这一句话有用。
