### ISSUE TITLE
Shadowroket+21.1.0仅可观看，其他动作均无效

### ISSUE THREAD

**Issue by kktoo21** [Semporia/TikTok-Unlock#311]
完完全全按照教程一步步来的，但最终的效果是可以观看，而且还很流畅。。。。但其他功能，比如搜索、登录、注册等均无效，都是显示网络问题。
已经逐字按照方法来，操作了3次了，效果一样，尝试换区从US换成JP，也是一样可以观看，其他功能无法实现。

求大神支招，谢谢！

**Comment by Semporia** [comment]
通过WEB端判断帐号是否异常！

**Comment by xunhuabai** [comment]
> 通过WEB端判断帐号是否异常！

我也遇到了此问题，并且我在之前一直都是全部功能正常的，只是近期突然只能在首页播放视频，搜索，登录这些功能全部显示无法链接到互联网。我尝试更新了最新的Shadowroket，卸载之后重装，按照更新的教程降级21.1.0（虽然之前一直都是这个版本没有进行更新），但是所有操作后仍然是只能首页播放视频，其他所有功能无法联网。账号在WEB端正常。

**Comment by xunhuabai** [comment]
> 通过WEB端判断帐号是否异常！

我再次测试了，用小火箭和LOON设置好之后使用V21均可以正常播放和浏览首页视频，但是无法登录无法搜索。升级到V27.1全部功能正常！但是只要后台杀一次之后，第二次打开tiktok直接黑屏，无法继续使用。先升级到V27.1所有功能正常后降级，覆盖安装V21后，又再次回到无法搜索，只能使用首页刷视频（此时账号不会退出登录，但是无法更新个人主页，所有首页以外的功能无法使用）

**Comment by Semporia** [comment]
降级是直接覆盖安装，还是TikTok全部卸载在安装21.1.0版本的！

**Comment by xunhuabai** [comment]
> 

第一次是覆盖安装，出现问题后卸载并重新安装21.0，仍然是最开始的问题，能看首页视频，无法搜索登陆。

**Comment by Phil2048** [comment]
同问

**Comment by Semporia** [comment]
21.1.0是可以正常登錄的。

**Comment by xunhuabai** [comment]
> 21.1.0是可以正常登錄的。

反复尝试，21.0只能停留在首页正常使用，可看视频但是无法登陆以及搜索。升级27.1全功能正常，但是只要后台杀一次就再也无法使用了…打开就黑屏。测试了多个网络环境，全部都是这种情况，应该可以排除网络原因。😭

**Comment by murderer17** [comment]
> > 21.1.0是可以正常登录的。
> 
> （21.1.0（）（21.1.0（）只只在使用使用使用，可首页使用使用使用正常正常视频视频但是但是无法登陆登陆以及。。。。升级升级升级升级升级升级升级升级升级全功能全功能测试了多个网络环境，全部都是这种情况，应该可以排除网络原因。😭

跟你一样的情况，21版本只能观看不能登录，升级最新以后可以登录，但是观看1-2次以后，关闭后台就不能观看了

**Comment by naiveclub** [comment]
> 

跟你差不多的情况。我iPhone和iPad都安装了抓包出来的21.1.0版本，iPhone2月14号登陆之后到现在圈X和小火箭都能使用，包括登陆点赞发视频；但是iPad相同的设置，只能浏览视频，无法登陆点赞，卸载重装tiktok、shadowrocket好几次了，还是老样子。账号网页端登录是没问题的，同样，iPhone上也在使用。不知道咋回事了

**Comment by naiveclub** [comment]
> > > 21.1.0是可以正常登录的。
> > 
> > 
> > （21.1.0（）（21.1.0（）只只在使用使用使用，可首页使用使用使用正常正常视频视频但是但是无法登陆登陆以及。。。。升级升级升级升级升级升级升级升级升级全功能全功能测试了多个网络环境，全部都是这种情况，应该可以排除网络原因。😭
> 
> 跟你一样的情况，21版本只能观看不能登录，升级最新以后可以登录，但是观看1-2次以后，关闭后台就不能观看了

跟你差不多的情况。我iPhone和iPad都安装了抓包出来的21.1.0版本，iPhone2月14号登陆之后到现在圈X和小火箭都能使用，包括登陆点赞发视频；但是iPad相同的设置，只能浏览视频，无法登陆点赞，卸载重装tiktok、shadowrocket好几次了，还是老样子。账号网页端登录是没问题的，同样，iPhone上也在使用。不知道咋回事了
