### ISSUE TITLE
可以用openwrt的privoxy进行rewrite吗

### ISSUE THREAD

**Issue by MoriMeina** [Semporia/TikTok-Unlock#320]
尝试在openwrt的privoxy进行rewrite，即不需要配置代理或软件

**Comment by Travel2Here** [comment]
> 尝试在openwrt的privoxy进行rewrite，即不需要配置代理或软件

你这是成了还是疑问？

**Comment by MoriMeina** [comment]
政策原因不在对此Issue进行更新
