### ISSUE TITLE
2023.2.24规则已失效

### ISSUE THREAD

**Issue by Amazon90** [Semporia/TikTok-Unlock#345]
Shadowrocket和Quantumult X按此说明的进行设定无一可以连接tiktok，个人认为是规则已经失效。
iOS15.7.3
tiktok28.2.0

**Comment by shmilyshirley** [comment]
tt的21.1.0版本就好了

**Comment by Amazon90** [comment]
有可以个签的ipa包吗？> tt的21.1.0版本就好了

**Comment by cxhaq** [comment]
最新版一般容易出现这个情况，试过好多次了

**Comment by seoho8908** [comment]
> Shadowrocket和Quantumult X按此说明的进行设定无一可以连接tiktok，个人认为是规则已经失效。
> iOS15.7.3
> tiktok28.2.0

![image](https://user-images.githubusercontent.com/37041520/221732644-3e9fd3c7-9236-4b6c-b250-2af5bc4c42c8.png)

V28.2，正常使用。软件：Surge
用的还是作者的TikTok模块

**Comment by ahuzh** [comment]
我也不好用，shadow

**Comment by CurtisWong458** [comment]
目前最新版本28.4.0依然正常刷

**Comment by seoho8908** [comment]
![image](https://user-images.githubusercontent.com/37041520/221827193-c7a5b73d-97b3-4ae0-8e72-0c5dc782ce99.png)
App Store 最新 V28.4，依旧可用。

**Comment by cxhaq** [comment]
说正常的用的肯定不是Shadowrocket吧

**Comment by Amazon90** [comment]
部分评论里说更新tiktok28.4.0也可正常使用，说明不能用和ios版本有关，我将ios升级到16.3.1，filter_remote、rewrite_remote、rewrite_local按仓库说明添加规则后依然是无法观看。

**Comment by Amazon90** [comment]
已经找到问题的关键，现在使用此仓库规则需要安装tiktok21.1.0，经该版本升级至最新版本tiktok，仅仅对shadowrocket之类的软件做设定并无用。如果安装旧版tiktok请大家下拉至此仓库最底部。
