### ISSUE TITLE
您好 请问tiktok如果官方更新后 这个就不能再用了吗？ 我是做海外运营的！还有是旧版的能提供下载？

### ISSUE THREAD

**Issue by ROWI7778** [Semporia/TikTok-Unlock#36]

**Comment by ROWI7778** [comment]
若是手机里本身已有tiktok17.3包含以下版本 没有删除 直接使用圈x的这份规则会不能使用吗？ 一定要编辑完再下载？

**Comment by CurtisWong458** [comment]
刚刚更新的最新19.5.0规则依然有效

**Comment by ROWI7778** [comment]
> 刚刚更新的最新19.5.0规则依然有效

好的 感谢 看来这次的规则代码挺给力的

**Comment by ROWI7778** [comment]
> 刚刚更新的最新19.5.0规则依然有效

你是直接更新能用还是卸载了重新下載19.5.0？ 解密跟信任要重用？

**Comment by CurtisWong458** [comment]
> > 刚刚更新的最新19.5.0规则依然有效
> 
> 你是直接更新能用还是卸载了重新下載19.5.0？ 解密跟信任要重用？

直接商店里面更新啊

**Comment by dyt-gift** [comment]
你好 请问打开的直播直接聊天字幕，没有画面是什么原因

CurtisWong458 ***@***.***>于2021年5月20日 周四上午9:34写道：

**Comment by ROWI7778** [comment]
> > > 刚刚更新的最新19.5.0规则依然有效
> 
> > 
> 
> > 你是直接更新能用还是卸载了重新下載19.5.0？ 解密跟信任要重用？
> 
> 
> 
> 直接商店里面更新啊

我知道 我的意思是之后如果又更新了规则不能用的话 应该也是要全卸载了 然后等规则更新文编辑完后再重新下载最新版对吧？ 还是一直测到不能用为止？

**Comment by ROWI7778** [comment]
應該是服務器穩定度的問題我可以幫你解決> 你好 请问打开的直播直接聊天字幕，没有画面是什么原因

**Comment by dyt-gift** [comment]
你好请问这个这个问题怎么解决

**Comment by CurtisWong458** [comment]
> > > > 刚刚更新的最新19.5.0规则依然有效
> > 
> > 
> > > 
> > 
> > 
> > > 你是直接更新能用还是卸载了重新下載19.5.0？ 解密跟信任要重用？
> > 
> > 
> > 直接商店里面更新啊
> 
> 我知道 我的意思是之后如果又更新了规则不能用的话 应该也是要全卸载了 然后等规则更新文编辑完后再重新下载最新版对吧？ 还是一直测到不能用为止？

不知道，反正我一直可以正常刷视频，刚刚又更新到19.5.1了

**Comment by ROWI7778** [comment]
更新这么快的吗？ 看来这次规则变得较给力
