### ISSUE TITLE
换区

### ISSUE THREAD

**Issue by hulesley** [Semporia/TikTok-Unlock#387]
好像用方法一的换区效果不是很明显，但是直播刷视频什么的比较流畅，方法二是能感觉到换区的，但是直播很卡，是不是我换哪个区开哪个重写就好了（Quantumult X）

**Comment by MissHe888** [comment]
我用的方法一，换的是韩国的，可是刷出的视频老是印度的！！怎么刷都是出的印度。。。。

**Comment by HentaiLSK** [comment]
> 我用的方法一，换的是韩国的，可是刷出的视频老是印度的！！怎么刷都是出的印度。。。。

哈哈哈哈

**Comment by xizelin** [comment]
这个方法还能用吗？我是16.4哪个方法都不行

**Comment by hulesley** [comment]
> 这个方法还能用吗？我是16.4哪个方法都不行

可以啊，我16.4.1上16.5都正常呀

**Comment by xizelin** [comment]
能分享你的机场吗

**Comment by hulesley** [comment]
> 我用的方法一，换的是韩国的，可是刷出的视频老是印度的！！怎么刷都是出的印度。。。。

节点问题？换了tk的语言之后感觉内容还好

**Comment by hulesley** [comment]
找一些大点的一二线的机场就可以了，也不贵，什么花云啊ytoo啥的> 能分享你的机场吗

**Comment by hulesley** [comment]
> 能分享你的机场吗

找一些大点的一二线的机场就可以了，也不贵，什么花云啊ytoo啥的> 能分享你的机场吗
