### ISSUE TITLE
最新版tiktok可以解锁了 可是抖音就打不开

### ISSUE THREAD

**Issue by magemini** [Semporia/TikTok-Unlock#42]
qx最新版 可解锁tiktok 
必须关了qx才能开抖音

**Comment by Semporia** [comment]
先安装抖音，然后安装TikTok。

**Comment by ROWI7778** [comment]
19.8.1來了 各位的都还行吗？！

**Comment by CurtisWong458** [comment]
> 19.8.1來了 各位的都还行吗？！

正常刷视频，直播都可以。

**Comment by ROWI7778** [comment]
好的 圈x的比小火箭流畅一点

**Comment by kissyouhunter** [comment]
> qx最新版 可解锁tiktok
> 必须关了qx才能开抖音

问题解决了吗
关掉mitm就没问题
重新都没打钩

**Comment by Semporia** [comment]
hostname = -*snssdk.com, -*amemv.com

添加即可

**Comment by Noe1Yoo** [comment]
不好意思，小火箭哪里添加hostname
