### ISSUE TITLE
完全按照教程步骤使用Shadowrocket, 登录提示Unable to authorize.Please try again. 并且会弹出账号状态：你的账号已退出登录，请尝试重新登录。

### ISSUE THREAD

**Issue by Qserver789** [Semporia/TikTok-Unlock#451]
我使用的Shadowrocket,相关配置等已按照文件指导完成。
安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。
升级为最新版本后提示无网络，期间Shadowrocket状态未改变。
在21.1.0版本登录时会提示  Unable to authorize.Please try again。   并且伴随着提示窗  账号状态  你的账号已退出登录，请尝试重新登录。    升级至最新版本也同样。
之前咨询过部分大神，告知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。
手机版本15.5.未越狱。
请各位大神们帮忙看一下是我哪里出了问题，怎么可以解决。谢谢！

**Comment by Qserver789** [comment]
> > 我使用的Shadowrocket,相关配置等已按照文件指导完成。安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。升级为最新版本后提示无网络，期间Shadowrocket状态未改变。在21.1.0版本登录时会提示无法授权。请重试。并且伴随着提示窗 账号状态 你的账号已退出登录，请尝试重新登录。升级至最新版本也同样。之前咨询过部分大神，告知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。手机版本15.5.未越狱。请各位大神们帮忙看一下是哪里出了问题，怎么可以解决。谢谢！
> 
> 还有一种可能性，邮箱账号未通过校验导致账号被锁，新账号注册登录试一下

尝试用其他谷歌账户注册，也是同样的提示同一个账号手机app登录不了，但是网页登录是正常的。

**Comment by Qserver789** [comment]
> > 我使用的Shadowrocket，相关配置等已按照文件指导完成。安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。升级为最新版本后提示无网络，期间Shadowrocket状态未改变。在21.1. 0版本登录时会提示无法授权，请重试。同时伴随着提示窗口 账号状态的账号你已退出登录，请尝试重新登录。升级至最新版本也同样。之前咨询过部分大神，得知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。手机版本15.5.未越狱。请各位大神们帮忙看看一下是我生长的问题，可以怎么解决。谢谢！
> 
> 还有一种可能性，邮箱账号未通过校验导致账号被锁，新账号注册登录试一下

问题找到了，是Shadowrocket配置分流的问题。

**Comment by Leven1113** [comment]
> > > 我使用的Shadowrocket，相关配置等已按照文件指导完成。安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。升级为最新版本后提示无网络，期间Shadowrocket状态未改变。在21.1. 0版本登录时会提示无法授权，请重试。同时伴随着提示窗口 账号状态的账号你已退出登录，请尝试重新登录。升级至最新版本也同样。之前咨询过部分大神，得知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。手机版本15.5.未越狱。请各位大神们帮忙看看一下是我生长的问题，可以怎么解决。谢谢！
> > 
> > 
> > 还有一种可能性，邮箱账号未通过校验导致账号被锁，新账号注册登录试一下
> 
> 问题找到了，是Shadowrocket配置分流的问题。

我也是这个问题登录不上，分流出了啥问题呀，可以分享一下吗

**Comment by shootingbrakeYY** [comment]
> > > > 我使用的Shadowrocket，相关配置等已按照文件指导完成。安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。升级为最新版本后提示无网络，期间Shadowrocket状态未改变。在21.1. 0版本登录时会提示无法授权，请重试。同时伴随着提示窗口 账号状态的账号你已退出登录，请尝试重新登录。升级至最新版本也同样。之前咨询过部分大神，得知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。手机版本15.5.未越狱。请各位大神们帮忙看看一下是我生长的问题，可以怎么解决。谢谢！
> > > 
> > > 
> > > 还有一种可能性，邮箱账号未通过校验导致账号被锁，新账号注册登录试一下
> > 
> > 
> > 问题找到了，是Shadowrocket配置分流的问题。
> 
> 我也是这个问题登录不上，分流出了啥问题呀，可以分享一下吗

我也是遇见这个问题了，请问有什么解决办法吗

**Comment by Qserver789** [comment]
> > 了，是Shadowrocket配置分流的问题。
> 
> 我也是这个问题登录不上，分流出了啥问题呀，可以分享一下吗

我也说不清分流哪出问题了。 我尝试不适用分流规则可以使用。后来就换了其他的分流规则就可以用了。

**Comment by Qserver789** [comment]
> > > > > 我使用的Shadowrocket，相关配置等已按照文件指导完成。安装tiktok21.1.0版本正常，视频可以刷一组无黑屏无卡顿。升级为最新版本后提示无网络，期间Shadowrocket状态未改变。 0版本登录时会提示无法授权，请重试。同时还提示账号状态的账号你已退出登录，请尝试重新登录。升级至最新版本也同样。之前咨询过部分大神，得知节点污染了，更换节点。尝试更换6个节点，结果一样没有变化。手机版本15.5.未越狱。请各位大神帮忙看看我生长的问题，可以怎么解决。谢谢！
> > > > 
> > > > 
> > > > 尚无此类权限，邮箱账号未通过保存导致账号被锁，新账号注册登录试一下
> > > 
> > > 
> > > 问题找到了，是Shadowrocket配置分流的问题。
> > 
> > 
> > 我也是这个问题登录不上，分流出了啥问题呀，可以分享一下吗
> 
> 我也是遇见这个问题了，请问有什么解决办法吗

我也说不清分流哪出问题了。 我尝试不适用分流规则可以使用。后来就换了其他的分流规则就可以用了。
