### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by henryl46** [Semporia/TikTok-Unlock#64]
前几天手贱卸载掉了旧版的tt 现在更新到了20.6.0 不知道大佬有更新安排吗？

**Comment by ROWI7778** [comment]
最新版本不支持了嗎？

**Comment by henryl46** [comment]
貌似是 我实在iphone上的小火箭配置的 配置完没办法用我以为是没拔卡的问题 换用ipad解锁发现也不行 您可以试一下

**Comment by ROWI7778** [comment]
刷機重新試試看

**Comment by henryl46** [comment]
谢谢 可以了 卸载完软件 重新部署然后重新安装就可以了 您可以更新到支持正式版20.6.0了哈哈哈

**Comment by yrzs** [comment]
我的 小火箭 也是20.6 刷不出来视频 ，请问你是怎么解决的

**Comment by henryl46** [comment]
方法是有效的 可能是步骤问题 一旦验证出问题就需要卸载tt+重装证书

**Comment by yrzs** [comment]
> 方法是有效的 可能是步骤问题 一旦验证出问题就需要卸载tt+重装证书

tt我卸载过了 小火箭怎么安装证书啊
