### ISSUE TITLE
去水印下载捷径无法使用

### ISSUE THREAD

**Issue by Mr-lins** [Semporia/TikTok-Unlock#85]
![IMG_9743](https://user-images.githubusercontent.com/26573094/133538791-870a1c31-6b71-41b5-b0c9-e79b754fed2f.PNG)
链接：https://vm.tiktok.com/ZMRQ9EnuX/

网页播放链接：https://www.tiktok.com/@melyssafreittas/video/6999166996961086726?sender_device=pc&sender_web_id=7007997263075083782&is_from_webapp=v1&is_copy_url=0

都是直接复制的tiktok的视频链接

有遇到同样问题的嘛？求解答

**Comment by Semporia** [comment]
每天限制一条
