### ISSUE TITLE
tiktok更新到21.5.0用不了啦

### ISSUE THREAD

**Issue by Sheepzzzy** [Semporia/TikTok-Unlock#90]

**Comment by iseeyou** [comment]
> 

是的，最新版用不了。

**Comment by Bluemiaocat** [comment]
@Semporia

**Comment by Kooeki123** [comment]
没高手

**Comment by francolamcn** [comment]
看来只能降级回去了，TikTok这次更新冲着这个bug来的？

**Comment by ROWI7778** [comment]
[URL Rewrite]
(?<=_region=)CN(?=&) JP 307
(?<=&mcc_mnc=)4 2 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[MITM]
hostname = *.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com

**Comment by Kylin93CN** [comment]
> [URL Rewrite] (?<=_region=)CN(?=&) JP 307 (?<=&mcc_mnc=)4 2 307 ^(https?://(tnc|dm)[\w-]+.\w+.com/.+)(?)(.+) $1$3 302 (^https?://*.\w{4}okv.com/.+&.+)(\d{2}.3.\d)(.+) $118.0$3 302
> 
> [MITM] hostname = _.tiktokv.com,_.byteoversea.com,*.tik-tokapi.com

试了，不行~

**Comment by Kylin93CN** [comment]
![A3CB5621C0E3618D7445222FA8D7282C](https://user-images.githubusercontent.com/18496145/137631392-e147936d-12a5-4014-a951-b03740d31787.png)
![66A1EC665F78518F6F1C92F293284582](https://user-images.githubusercontent.com/18496145/137631397-26e1ae2b-a080-4cd4-9fa0-d5914b252cc6.png)

使用这个配置ok的  亲测，2021年10月17日22:18:47

**Comment by ROWI7778** [comment]
這是Shadowrocket
的

**Comment by HuimingChu** [comment]
21.5暂时没有方法出来，大家别盲目按照上面的方法试，是不是真的不说，能成功那是你运气好，好多捣乱的。建议卸载21.5，然后用抓包工具下载21.1版本安装，在有效的新方法出来之前不要升级。

**Comment by zhuerba** [comment]
ios怎么退回21.1

**Comment by seoho8908** [comment]
要自己抓旧版本App的包。> ios怎么退回21.1

**Comment by francolamcn** [comment]
有没有直链下载的方式搞到21.1.0的版本，就像微信多开安装那个操作，我看到好多要用到iTunes，好鬼麻烦

**Comment by Zoooooooooo** [comment]
期待有大神能把21.5赶紧搞定~~

**Comment by seoho8908** [comment]
> 期待有大神能把21.5赶紧搞定~~

跟你一样。

**Comment by francolamcn** [comment]
> > 有没有直链下载的方式搞到21.1.0的版本，就像微信多开安装那个操作，我看到好多要用到iTunes，好鬼麻烦
> 
> 没有。iOS App有Apple ID验证的。你用别人账号下载的App没法用。

我自己搞了一个ipa，直链下载安装，不过确实只有我的ID才能使用~
