### ISSUE TITLE
windows快速下载旧版本ipa

### ISSUE THREAD

**Issue by iseeyou** [Semporia/TikTok-Unlock#94]
itunes企业版下载：https://support.apple.com/zh-cn/HT208079
iOS旧版应用下载v5.1：https://xiaogao.lanzoui.com/b0cwjvjuj
使用 iOS旧版应用下载 可以免抓包，很方便，可能报毒，不信任可以使用虚拟机执行操作。

安装itunes，登录自己的apple id。搜索进去tiktok下载页面，待用。。。
打开 iOS旧版应用下载v5.1，搜索tiktok 选择美区，搜索结果选择旧版本 TikTok 21.1.0 下载。
返回itunes，点击下载即可，下载后查看文件名是否为 TikTok 21.1.0 ，然后用爱思助手安装即可。注意吧iphone的appstore自动更新软件关闭。

**Comment by Xben-H** [comment]
下载了打不开是什么原因。防火墙关了也不行
