### ISSUE TITLE
tiktok 21.7版本有破解方法嘛

### ISSUE THREAD

**Issue by Mr-lins** [Semporia/TikTok-Unlock#97]

**Comment by Star022** [comment]
+1

從我的iPhone傳送

**Comment by Mr-lins** [comment]
我在YouTube上面看到有降级ipa的教程(https://www.youtube.com/watch?v=3CNaSpEIWYA&t=187s)，但是有向上兼容的方法就完美了。

**Comment by 4rat** [comment]
同求 +1

**Comment by 4rat** [comment]
> 我在YouTube上面看到有降级的教程，但是有升级的ipa版本的方法就完美了。 [https://www.com.com/watch?v3CNaSpEIWYA&t=187s](https://www.youtube.com/watch?v=3CNaSpEIWYA&t=187s)

这个测试可行吗？

**Comment by Mr-lins** [comment]
> > 我在YouTube上面看到有降级的教程，但是有升级的ipa版本的方法就完美了。 [https://www.com.com/watch?v3CNaSpEIWYA&t=187s](https://www.youtube.com/watch?v=3CNaSpEIWYA&t=187s)
> 
> 这个测试可行吗？

我没试过，只是看到有这样的教程

**Comment by Fetiz** [comment]
> > 我在YouTube上面看到有降级的教程，但是有升级的ipa版本的方法就完美了。 [https://www.com.com/watch?v3CNaSpEIWYA&t=187s](https://www.youtube.com/watch?v=3CNaSpEIWYA&t=187s)
> 
> 这个测试可行吗？

测试可行。但目前关注有问题。点击后无法关注。不如花几百块买个pixel不插卡专门刷抖音

**Comment by HideNameUser** [comment]
同求

**Comment by 404user** [comment]
这次真奇怪，升级了这么久居然没人破解出来？

**Comment by csc-EricWu** [comment]
我降级成功了。
