### ISSUE TITLE
依旧无法使用

### ISSUE THREAD

**Issue by Sheepzzzy** [Semporia/TikTok-Unlock#99]
22的版本使用上述方法，试了很多遍还是看不了什么都刷不出来

**Comment by isbyhr** [comment]
22.0用surge弄了半天也不行啊

**Comment by msn1983aa** [comment]
可能这个办法是针对QX的，filter_remote在小火箭是没有的。

**Comment by kylehoo** [comment]
> 22.0用surge弄了半天也不行啊

我的也是，手贱点了升级22.0
